package com.ityun.zhihuiyun.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ityun.zhihuiyun.bean.RemarkName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "REMARK_NAME".
*/
public class RemarkNameDao extends AbstractDao<RemarkName, Long> {

    public static final String TABLENAME = "REMARK_NAME";

    /**
     * Properties of entity RemarkName.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, int.class, "userId", false, "USER_ID");
        public final static Property RemarkAccountId = new Property(2, int.class, "remarkAccountId", false, "REMARK_ACCOUNT_ID");
        public final static Property RemarkName = new Property(3, String.class, "remarkName", false, "REMARK_NAME");
    }


    public RemarkNameDao(DaoConfig config) {
        super(config);
    }
    
    public RemarkNameDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"REMARK_NAME\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"USER_ID\" INTEGER NOT NULL ," + // 1: userId
                "\"REMARK_ACCOUNT_ID\" INTEGER NOT NULL ," + // 2: remarkAccountId
                "\"REMARK_NAME\" TEXT);"); // 3: remarkName
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"REMARK_NAME\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RemarkName entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getRemarkAccountId());
 
        String remarkName = entity.getRemarkName();
        if (remarkName != null) {
            stmt.bindString(4, remarkName);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RemarkName entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getUserId());
        stmt.bindLong(3, entity.getRemarkAccountId());
 
        String remarkName = entity.getRemarkName();
        if (remarkName != null) {
            stmt.bindString(4, remarkName);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RemarkName readEntity(Cursor cursor, int offset) {
        RemarkName entity = new RemarkName( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getInt(offset + 1), // userId
            cursor.getInt(offset + 2), // remarkAccountId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // remarkName
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RemarkName entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.getInt(offset + 1));
        entity.setRemarkAccountId(cursor.getInt(offset + 2));
        entity.setRemarkName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RemarkName entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RemarkName entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RemarkName entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
